### ISSUE TITLE
DEFAULT_TEQUILA_MIRROR_OPTIONS contract addresses missing

### ISSUE THREAD

**Issue by OhmRoger** [Mirror-Protocol/mirror.js#15]
Logger.log(DEFAULT_TEQUILA_MIRROR_OPTIONS);

Log: 
  collector: 'terra1v046ktavwzlyct5gh8ls767fh7hc4gxc95grxy',
  community: 'terra10qm80sfht0zhh3gaeej7sd4f92tswc44fn000q',
  factory: 'terra10l9xc9eyrpxd5tqjgy6uxrw7dd9cv897cw8wdr',
  gov: 'terra12r5ghc6ppewcdcs3hkewrz24ey6xl7mmpk478s',
  mint: 'terra1s9ehcjv0dqj2gsl72xrpp0ga5fql7fj7y3kq3w',
  oracle: 'terra1uvxhec74deupp47enh7z5pk55f3cvcz8nj4ww9',
  collateralOracle: 'terra00',
  staking: 'terra1a06dgl27rhujjphsn4drl242ufws267qxypptx',
  lock: 'terra00',
  mirrorToken: 'terra10llyp6v3j3her8u3ce66ragytu45kcmd9asj3u',
  terraswapFactory: 'terra18qpjm4zkvqnpjpw0zn0tdr8gdzvt8au35v45xf',
  airdrop: 'terra1p6nvyw7vz3fgpy4nyh3q3vc09e65sr97ejxn2p',
  shortReward: 'terra00',

**Comment by 0xslipk** [comment]
@OhmRoger thank you for reach out. You're right, They are missing. I will fix it.
