### ISSUE TITLE
Mirror API forbidden

### ISSUE THREAD

**Issue by RylandCapital** [Mirror-Protocol/mirror.js#9]
Hello,

I was working on a mirror app and I think I might have hit a rate limit for the API? everything jsut stopped working and said forbidden when I try to go to https://graph.mirror.finance/graphql. any idea what the limits are incase I did hit them? thanks!

**Comment by 0xslipk** [comment]
Hello @RylandCapital are you using mirror.js or Mirror API?, because if you have problem with Mirror API. You can open an issue in [mirror-graph](https://github.com/Mirror-Protocol/mirror-graph/issues) repository 😄. Hope that helps.
